#!/usr/bin/env php
<?php

// change the following paths if necessary
$yiic='D:\xampp\htdocs\www\yii\yii-1.1.8.r3324\framework\yiic.php';
$config=dirname(__FILE__).'/config/console.php';

require_once($yiic);
